# Generated by Django 2.0.1 on 2019-07-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190705_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar paramento NF-e'), ('permissao2', 'Permissao 2'), ('permissao3', 'Permissao 3'))},
        ),
    ]
