# Generated by Django 2.0.1 on 2019-07-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20190704_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': {('deletar_clientes', 'Deletar cliente')}},
        ),
    ]
